# Generated by Django 4.2.7 on 2023-12-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=13),
        ),
    ]
